// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAmCxzfFMaJJ4RTPrPsyqNtp8i05KcdEM',
    appId: '1:51705683787:web:79dc9d4f2c05c86ac692ce',
    messagingSenderId: '51705683787',
    projectId: 'synca-app-a7809',
    authDomain: 'synca-app-a7809.firebaseapp.com',
    storageBucket: 'synca-app-a7809.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYQd8NN1KOw7dIygh8wmoseGA8bbXv3YA',
    appId: '1:51705683787:android:a39ab0df2ef031f6c692ce',
    messagingSenderId: '51705683787',
    projectId: 'synca-app-a7809',
    storageBucket: 'synca-app-a7809.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASfSgMx41sewLbQbtEQpPg-4vAmRBJPuw',
    appId: '1:51705683787:ios:e32d70ee2dfd80ecc692ce',
    messagingSenderId: '51705683787',
    projectId: 'synca-app-a7809',
    storageBucket: 'synca-app-a7809.firebasestorage.app',
    iosBundleId: 'com.example.syncaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASfSgMx41sewLbQbtEQpPg-4vAmRBJPuw',
    appId: '1:51705683787:ios:e32d70ee2dfd80ecc692ce',
    messagingSenderId: '51705683787',
    projectId: 'synca-app-a7809',
    storageBucket: 'synca-app-a7809.firebasestorage.app',
    iosBundleId: 'com.example.syncaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAmCxzfFMaJJ4RTPrPsyqNtp8i05KcdEM',
    appId: '1:51705683787:web:fc3600e42719326fc692ce',
    messagingSenderId: '51705683787',
    projectId: 'synca-app-a7809',
    authDomain: 'synca-app-a7809.firebaseapp.com',
    storageBucket: 'synca-app-a7809.firebasestorage.app',
  );
}
